version: "3"

services:
    elastic-search:
        # image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
        container_name: node01
        environment:
            - node.name=node01
            - cluster.name=es-cluster-7
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
            - xpack.security.enabled=false # disable auth, tls/https
            # - xpack.security.transport.ssl.enabled=false
            # - xpack.security.http.ssl.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        # volumes:
        #     - es-data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    mongo-search:
        container_name: mongo-search
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - user-data:/data/db

    user-search:
        container_name: user-search
        restart: always
        build: ./
        ports:
            - "8080:8080"
        depends_on:
            - mongo-search
        volumes:
            - ./:/app

volumes:
    user-data:
    es-data01:
